<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_viewer_app_description'] = 'The Bandwidth Viewer draws a live graph of your interface bandwidth. This helps to determine the current speed of your interfaces and identify bandwidth problems across the network.';
$lang['bandwidth_viewer_app_name'] = 'Bandwidth Viewer';
$lang['bandwidth_viewer_series'] = 'Graph Series';
$lang['bandwidth_viewer_series_help'] = 'Select graph series';
$lang['bandwidth_viewer_title'] = 'Bandwidth Graph (Mbps)';
