<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_viewer_app_description'] = 'Средство просмотра пропускной способности рисует живой график пропускной способности канала интерфейса. Это помогает определить текущую скорость ваших интерфейсов и определить пропускную проблему в сети.';
$lang['bandwidth_viewer_app_name'] = 'Смотреть объем трафика';
$lang['bandwidth_viewer_series'] = 'График интерфейса';
$lang['bandwidth_viewer_series_help'] = 'Выберите интерфейс для графика';
$lang['bandwidth_viewer_title'] = 'График пропускной способность (Mbps)';
