<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['bandwidth_viewer_app_description'] = 'Podgląd pasma rysuje wykresy ruchu na interfejsach sieciowych w czasie rzeczywistym. Pomaga to określić aktualną prędkość Twoich interfejsów i zidentyfikować problemy związane z przepustowością wewnątrz Twojej sieci.';
$lang['bandwidth_viewer_app_name'] = 'Podgląd pasma';
$lang['bandwidth_viewer_series'] = 'Serie wykresu';
$lang['bandwidth_viewer_series_help'] = 'Wybierz serie wykresu';
$lang['bandwidth_viewer_title'] = 'Wykres pasma (Mbps)';
